url: "https://trips.madebykind.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Kind on tour" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-postcss
  - jekyll-minifier
image_base:  https://mathayward.imgix.net/
exclude:
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
